name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14-alpine
	env:
	   POSTGRES_USER: root
	   POSTGRES_PASSWORD: baoduong1011
	   POSTGRES_DB: simple_bank
       
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Run Migration
      uses: make migrateup

    - name: Test
      run: make test

